on:
  push:
    branches:
      - 'main'
  # Enable manual run; must be in main branch to be available
  workflow_dispatch:
jobs:
  ecr-deploy:
    uses: nationalarchives/da-tre-github-actions/.github/workflows/docker-build-and-ecr-deploy.yml@0.0.5
    with:
      docker_image_name: 'tre-judgment-packer'
      build_dir: 'tre-judgment-packer'
      ecr_registry_path: 'tre-v2'
